def find_error():
    numbers = [10, 20, 30]
    result = numbers[2] + 5
    return result


find_error()
